### ISSUE TITLE
Library does not work due to compilation on older node.js version

### ISSUE THREAD

**Issue by Zeprakadebra** [nebrius/raspi-soft-pwm#5]
Hi nebrius,
many thanks for your great work.
I try to control my PI4-fans (I use 2 NF-a9-5v-pwm fans from noctua [https://noctua.at/de/nf-a9-5v-pwm] built in one case) using your great library. However when starting the code in node.js i got the exception that the library is compiled on an older version of node.js and therefore is not compatible with my current node.js version.

I tried to fix this issue with 'npm rebuild' however it does not work.

Can you pls let me know how I can rebuild your library on my latest node.js version?

Your quick reply is highly appreciated.

Kind regards,
Zebrakadebra

**Comment by nebrius** [comment]
Try deleting your node_modules folder and reinstalling it. I've found `npm rebuild` isn't always that effective.

If that doesn't work, there's not much else I can do because this library doesn't have any C++ in it. One of the dependencies I use does though and is what's giving you the error, so at that point you'll want to file an issue at https://github.com/fivdi/pigpio

**Comment by Zeprakadebra** [comment]
Hi nebrius,

many thanks for your quick reply.

Deleting the node_modules folder and reinstalling it, did not fix this.

It makes sense to open an issue at https://github.com/fivdi/pigpio.
I am going to do it know. You can close this one.

Thanks!

Kind regards,
Zebrakadebra
